
export const	SEND_REQUEST = 'SEND_REQUEST';
export const	RECEIVE_REQUEST = 'RECEIVE_REQUEST';
export const  GET_SURVEY_REQUEST_SUCCESS = 'GET_SURVEY_REQUEST_SUCCESS';
export const	GET_SURVEY_REQUEST_ERROR = 'GET_SURVEY_REQUEST_ERROR';
export const	CHANGE_QUESTION = 'CHANGE_QUESTION';
export const	CHOOSE_ANSWER = 'CHOOSE_ANSWER';
export const	RESET_SURVEY = 'RESET_SURVEY';
export const	FINISH_SURVEY = 'FINISH_SURVEY';
